import mongoose from "../config/mongodb.js";
import TypeCuisine from "../models/TypeCuisine.js";

const TypeCuisineSeeder = async () => {
  const model = mongoose.model("TypeCuisine");
  const data = [
    { libelle: "A la bière" },
    { libelle: "Africaine" },
    { libelle: "Algérienne" },
    { libelle: "Alsacienne" },
    { libelle: "Américaine" },
    { libelle: "Antillaise" },
    { libelle: "Argentine" },
    { libelle: "Asiatique" },
    { libelle: "Bagels" },
    { libelle: "Bar à vins" },
    { libelle: "Basque" },
    { libelle: "Belge" },
    { libelle: "Bio" },
    { libelle: "Bistronomique" },
    { libelle: "Bourguignonne" },
    { libelle: "Braserade" },
    { libelle: "Bretonne" },
    { libelle: "Britannique" },
    { libelle: "Brésilienne" },
    { libelle: "Buffet" },
    { libelle: "Burger Bar" },
    { libelle: "Chinoise" },
    { libelle: "Corse" },
    { libelle: "Coréenne" },
    { libelle: "Créative" },
    { libelle: "Créole" },
    { libelle: "Crêperie" },
    { libelle: "Cubaine" },
    { libelle: "Diététique" },
    { libelle: "Du monde" },
    { libelle: "Espagnole" },
    { libelle: "Exotique" },
    { libelle: "Fait maison" },
    { libelle: "Fast food" },
    { libelle: "Flamande-régionale" },
    { libelle: "Fondue" },
    { libelle: "Food Truck" },
    { libelle: "Française" },
    { libelle: "Friterie" },
    { libelle: "Fromage" },
    { libelle: "Fruits de mer" },
    { libelle: "Gastronomique" },
    { libelle: "Grecque" },
    { libelle: "Grillades" },
    { libelle: "Hallal" },
    { libelle: "Indienne" },
    { libelle: "Pakistanaise" },
    { libelle: "Indonésienne" },
    { libelle: "Internationale" },
    { libelle: "Italienne" },
    { libelle: "Japonaise" },
    { libelle: "Latino-Américaine" },
    { libelle: "Libanaise" },
    { libelle: "Lorraine" },
    { libelle: "Lyonnaise" },
    { libelle: "Marocaine" },
    { libelle: "Mexicaine" },
    { libelle: "Mongole" },
    { libelle: "Moules" },
    { libelle: "Méditerranéenne" },
    { libelle: "New-yorkaise" },
    { libelle: "Niçoise" },
    { libelle: "Normande" },
    { libelle: "Orientale" },
    { libelle: "Pates" },
    { libelle: "Pays de l’Est" },
    { libelle: "Pierrade" },
    { libelle: "Pizza" },
    { libelle: "Plancha" },
    { libelle: "Polonaise" },
    { libelle: "Portugaise" },
    { libelle: "Provençale" },
    { libelle: "Restaurant rapide" },
    { libelle: "Russe" },
    { libelle: "Régionale" },
    { libelle: "Réunionnaise" },
    { libelle: "Saine" },
    { libelle: "Salon de thé" },
    { libelle: "Sans gluten" },
    { libelle: "Savoyarde" },
    { libelle: "Scandinave" },
    { libelle: "Suisse" },
    { libelle: "Sushis" },
    { libelle: "Sénégalaise" },
    { libelle: "Tapas" },
    { libelle: "Tartes flambées" },
    { libelle: "Tartines" },
    { libelle: "Tchèque" },
    { libelle: "Thaïlandaise" },
    { libelle: "Traditionnelle" },
    { libelle: "Tunisienne" },
    { libelle: "Turque" },
    { libelle: "Viandes" },
    { libelle: "Vietnamienne" },
    { libelle: "Vosgienne" },
    { libelle: "Végétarienne" },
    { libelle: "Wok" },
    { libelle: "De Bistrot" },
    { libelle: "De Brasserie" },
    { libelle: "De Saison" },
    { libelle: "Du Maghreb" },
    { libelle: "Du Marché" },
    { libelle: "Du Sud-Ouest" },
    { libelle: "Du Terroir" },
    { libelle: "Kashere" },
    { libelle: "Ouzbèke" },
  ];

  if (model) {
    const result = await TypeCuisine.insertMany(data);
    if (result) {
      console.log("TypeCuisineSeeder effectué");
    } else {
      console.log("TypeCuisine Model non trouvé");
    }
  }
};
export default TypeCuisineSeeder;
